### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by sugatoray** [seungjaeryanlee/chocolate#1]
This library does not have any license file. Please add one.

**Comment by sugatoray** [comment]
cc: @seungjaeryanlee

**Comment by seungjaeryanlee** [comment]
Thank you. I added MIT license, but if it is not permissive enough, please ping me!

**Comment by sugatoray** [comment]
That should be fine. Thank you.

**Comment by sugatoray** [comment]
Please leave a comment here with a mention to me, once you have pushed the release to PyPI.
